services:

  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=$PID
      - GUID=$GID
      - TZ=Europe/London
      - SERVERURL=${WIREGUARD_SERVER_URL}
      - SERVERPORT=${WIREGUARD_SERVER_PORT}
      - PEERS=2
      - PEERDNS=8.8.8.8
      - INTERNAL_SUBNET=10.10.10.0
    volumes:
      - $HOME/wireguard:/config
    ports:
      # server port above and host port here are to be set the same, but container port must always be the usual
      - "5000:5000"
      - $WIREGUARD_SERVER_PORT:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  wireguard-ui:
    image: ngoduykhanh/wireguard-ui
    container_name: ui
    depends_on:
      - wireguard
    cap_add:
      - NET_ADMIN
    network_mode: service:wireguard
    environment:
      - SENDGRID_API_KEY
      - EMAIL_FROM_ADDRESS
      - EMAIL_FROM_NAME
      - SESSION_SECRET
      - WGUI_USERNAME=admin
      - WGUI_PASSWORD=password
      - WG_CONF_TEMPLATE
      - WGUI_MANAGE_START=true
      - WGUI_MANAGE_RESTART=true
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: 50m
    volumes:
      - $HOME/wireguard-ui:/app/db
      - $HOME/wireguard:/etc/wireguard


networks:
  wireguard_net:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.10.0/24
