version: '3.6'
services:
    # games
    factorio:
        image: goofball222/factorio:latest
        ports:
            - "27015:27015"
            - "34197:34197/udp"
        volumes:
            - /var/factorio/vanilla/config:/opt/factorio/config
            - /var/factorio/vanilla/mods:/opt/factorio/mods
            - /var/factorio/vanilla/saves:/opt/factorio/saves
    factorio_seablock:
        image: goofball222/factorio:latest
        ports:
            - "27015:27015"
            - "34197:34197/udp"
        volumes:
            - /var/factorio/seablock/config:/opt/factorio/config
            - /var/factorio/seablock/mods:/opt/factorio/mods
            - /var/factorio/seablock/saves:/opt/factorio/saves
    minecraft:
        image: itzg/minecraft-server:latest
        ports:
            - "25565:25565"
        environment:
            - EULA=true
        volumes:
            - /var/minecraft:/data
    # web servers
    apache:
        image: httpd:2.4
        ports:
            - "80:80"
        volumes:
            - /var/httpd:/usr/local/apache2/htdocs

