services:
  wireguard:
    image: linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles  # Change to your time zone
    volumes:
      - ./wg-config:/config
      - /lib/modules:/lib/modules
    ports:
      - "0.0.0.0:8080:${QBT_WEBUI_PORT}"
      - "[::1]:8080:${QBT_WEBUI_PORT}"
      # - "12345:12345/udp"  # Replace with your VPN's port-forwarding configuration
      - "51820:51820/udp"  # Default Wireguard port
    networks:
      - qbt-wg-network
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1  # Required for Wireguard container. See https://github.com/linuxserver/docker-wireguard
      - net.ipv6.conf.all.disable_ipv6=0  # Required for IPv6 capability
    restart: unless-stopped

  qbittorrent-nox:
    container_name: qbittorrent-nox
    environment:
      - PUID=1000
      - PGID=1000
      - QBT_LEGAL_NOTICE=${QBT_LEGAL_NOTICE}
      - QBT_VERSION=${QBT_VERSION}
      - QBT_WEBUI_PORT=${QBT_WEBUI_PORT}
      - TZ=America/Los_Angeles  # Change to your time zone
    image: qbittorrentofficial/qbittorrent-nox:${QBT_VERSION}
    network_mode: service:wireguard
    read_only: true
    restart: unless-stopped
    stop_grace_period: 30m
    tmpfs:
      - /tmp
    volumes:
      - ${QBT_CONFIG_PATH}:/config
      - ${QBT_DOWNLOADS_PATH}:/downloads

networks:
  qbt-wg-network:
    enable_ipv6: true
    ipam:
      config:
        # Set this to a subnet that won't be used by any GUA address. See the explanation below.
        - subnet: d000::/112  # Change to your favorite CIDR
