services:
  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
        #    devices:
        #      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000
      - 9999:9999
      - 8090:8090
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - SERVER_CITIES=Manchester
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PGID=1001
      - TZ=Europe/London
      - WEBUI_PORT=8090
    volumes:
      - /home/jake/qbittorrent:/config
      - /var/media:/data/torrents
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped
