volumes:
  portainer_data:

services:

  portainer:
    image: portainer/portainer-ce
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:0.20.6
    environment:
      PUID: $PID
      PGID: $GID
      APP_KEY: $SPEEDTEST_TRACK_APP_KEY
      DB_CONNECTION: sqlite
      APP_DEBUG: true
      SPEEDTEST_SCHEDULE: "24 */6 * * *"
    volumes:
      - $HOME/speedtest/config:/config
    ports:
      - 8085:80
      - 8443:443
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    environment:
      PUID: $PID
      PGID: $GID
    ports:
      - 80:3000
    volumes:
      - $HOME/homepage/config:/app/config # Make sure your local config directory exists
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
      # read only system mounts for resources widget
      #      - /home:/mnt/ro_home:ro
      #      - /var/media:/mnt/ro_media:ro
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
        #    devices:
        #      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000
      - 9999:9999
      - 8090:8090
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - VPN_ENDPOINT_PORT=51820
      - SERVER_COUNTRIES=UK
      - SERVER_CITIES=Manchester
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent:4.5.2
    container_name: qbittorrent
    environment:
      - PGID=1001
      - TZ=Europe/London
      - WEBUI_PORT=8090
    volumes:
      - /home/jake/qbittorrent:/config
      - /var/media:/data/torrents
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

  syncthing:
    image: lscr.io/linuxserver/syncthing:latest
    container_name: syncthing
    environment:
      - PUID=$PID
      - PGID=$GID
        # - TZ=Etc/UTC
    volumes:
      - $HOME/syncthing/config:/config
      - /var/media/Syncthing:/data1
    ports:
      - 8384:8384
      - 22000:22000/tcp
      - 22000:22000/udp
      - 21027:21027/udp
    restart: unless-stopped

