volumes:
  portainer_data:

services:

  portainer:
    image: portainer/portainer-ce
    ports:
      - 9001:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    restart: unless-stopped

  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:0.20.6
    environment:
      PUID: $PID
      PGID: $GID
      APP_KEY: $SPEEDTEST_TRACK_APP_KEY
      DB_CONNECTION: sqlite
      APP_DEBUG: "true"
      SPEEDTEST_SCHEDULE: "24 */6 * * *"
    volumes:
      - $HOME/speedtest/config:/config
    ports:
      - 8085:80
      - 8443:443
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: homepage.secrets
    environment:
      PUID: $PID
      PGID: $GID
    ports:
      - 80:3000
    volumes:
      - $HOMEPAGE_CONFIG_DIR:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

  gluetun:
    image: qmcgaw/gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8000:8000
      - 9999:9999
      - 8090:8090
    environment:
      - VPN_SERVICE_PROVIDER=mullvad
      - VPN_TYPE=wireguard
      - WIREGUARD_PRIVATE_KEY=${WIREGUARD_PRIVATE_KEY}
      - WIREGUARD_ADDRESSES=${WIREGUARD_ADDRESSES}
      - VPN_ENDPOINT_PORT=51820
      - SERVER_COUNTRIES=UK
      - SERVER_CITIES=Manchester
    restart: always

  qbittorrent:
    image: linuxserver/qbittorrent
    container_name: qbittorrent
    environment:
      PUID: $PID
      PGID: $GID
      TZ: Europe/London
      WEBUI_PORT: 8090
    volumes:
      - /home/jake/qbittorrent2:/config
      - /var/media:/data/torrents
    network_mode: service:gluetun
    depends_on:
      gluetun:
        condition: service_healthy
    restart: unless-stopped

