volumes:
  portainer_data:

services:

  #portainer:
  #  image: portainer/portainer-ce
  #  ports:
  #    - 9001:9000
  #  volumes:
  #    - /var/run/docker.sock:/var/run/docker.sock
  #    - portainer_data:/data
  #  restart: unless-stopped

  speedtest:
    image: lscr.io/linuxserver/speedtest-tracker:0.20.6
    environment:
      PUID: $PID
      PGID: $GID
      APP_KEY: $SPEEDTEST_TRACK_APP_KEY
      DB_CONNECTION: sqlite
      APP_DEBUG: "true"
      SPEEDTEST_SCHEDULE: "24 */6 * * *"
    volumes:
      - $HOME/speedtest/config:/config
    ports:
      - 8085:80
      - 8443:443
    restart: unless-stopped

  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    container_name: homepage
    env_file: homepage.secrets
    environment:
      PUID: $PID
      PGID: $GID
    ports:
      - 80:3000
    volumes:
      - $HOMEPAGE_CONFIG_DIR:/app/config
      - /var/run/docker.sock:/var/run/docker.sock:ro # optional, for docker integrations
    restart: unless-stopped

