volumes:
  portainer_data:

services:
  portainer:
   image: portainer/portainer-ce
   ports:
     - 9001:9000
   volumes:
     - /var/run/docker.sock:/var/run/docker.sock
     - portainer_data:/data
   restart: unless-stopped