version: '3.6'
services:
    vpn:
        image: bantam/docker-piavpn-arm
        ports:
            - "8112:8112"
            - "1080:1080"
            - "58846:58846"
        restart: always
        dns:
            - 8.8.8.8
        cap_add:
            - NET_ADMIN
        env_file:
            - $HOME/vpn.env
            # specify PIA_USER, PIA_PASS, DELUGE_UID, DELUGE_GID in here
        environment:
            - HOST_SUBNET=192.168.0.0/24
            - PIA_GATEWAY=fi.privateinternetaccess.com
        volumes:
            - /var/media:/torrents
            - /var/deluge:/app/deluge
            - /etc/localtime:/etc/localtime:ro
