services:

  papermc:
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    ports:
      - "25565:25565"
      - "8100:8100"
    environment:
      EULA: "TRUE"
      TYPE: "PAPER"
      VERSION: "1.21"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - $HOME/papermc:/data
      - /var/media/MinecraftBackups:/data/plugins/Backuper/Backups
    restart: unless-stopped

